name: qaz_mebel
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  pdf: ^3.10.1

  share_extend: ^2.0.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  provider: ^6.0.5
  firebase_storage: ^11.0.16
  fluttertoast: ^8.2.1
  persistent_bottom_nav_bar: ^5.0.2
  image_picker: ^0.8.7+1
  firebase_messaging: ^14.4.0
  flutter_stripe: ^9.0.0+1
  http: ^0.13.5
  flutter_native_splash: ^2.2.19
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.0"

flutter_icons:
  android: true
  image_path_android: "assets/launcher/icon.png"

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          style: normal
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
          style: normal
    - family: Times
      fonts:
        - asset: assets/fonts/Times-New-Roman.ttf
          style: normal
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf



  assets:
    - assets/images/
    - assets/launcher/



